# Generated by Django 4.2.7 on 2025-09-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('celery_task_name', models.CharField(max_length=200, unique=True)),
                ('input_schema', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'task_definitions',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='task_defini_is_acti_e4ce22_idx'), models.Index(fields=['celery_task_name'], name='task_defini_celery__b8a632_idx')],
            },
        ),
    ]
