# Generated by Django 4.2.7 on 2025-09-20 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedules', '0001_initial'),
        ('executions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionlog',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='schedules.schedule'),
        ),
        migrations.AddIndex(
            model_name='executionlog',
            index=models.Index(fields=['schedule', 'started_at'], name='execution_l_schedul_da849e_idx'),
        ),
        migrations.AddIndex(
            model_name='executionlog',
            index=models.Index(fields=['status'], name='execution_l_status_d8a5a0_idx'),
        ),
        migrations.AddIndex(
            model_name='executionlog',
            index=models.Index(fields=['celery_task_id'], name='execution_l_celery__d1954b_idx'),
        ),
    ]
