# Generated by Django 4.2.7 on 2025-09-20 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['user', 'is_active'], name='schedules_user_id_ecd754_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['task_definition'], name='schedules_task_de_5831dd_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['created_at'], name='schedules_created_4bfac2_idx'),
        ),
    ]
